### ISSUE TITLE
Adding https example . Best way is ? 

### ISSUE THREAD

**Issue by gedw99** [egregors/passkey#12]
Only tested on local lan to laptop but should really work.

Wondering if it needs https, or its the secure cookie problem... 

https://caniuse.com/?search=webauthn shows it should work :)

![photo_2024-08-06 13 48 38](https://github.com/user-attachments/assets/4a1246ef-9b77-40ea-9227-f40d15277855)

**Comment by egregors** [comment]
I'm going to try to deploy _example app under Lets Encrypt SSL to be sure that the problem is not in HTTPs.

**Comment by egregors** [comment]
I can confirm, that this issue is not reproducing when app with `passkey` deployed with SSL. Some info in PR #17 

Let's rename this issue and use it to discuss adding HTTPS example?

**Comment by egregors** [comment]
> Will you add a traefik sample then?

Absolutely! It'll be great if you can do that. Let's put all this stuff inside `_example`. It could be a part of #19 activity.

How do you think, should we separate examples in `_example` (I mean: one for just go app, one – with SSL on localhost, one – for prod ready and so on) or it looks like overkill for now?
