### ISSUE TITLE
caddy and https fails with "can't finish registration: Error validating origin"

### ISSUE THREAD

**Issue by gedw99** [egregors/passkey#16]
Just trying things out so its easy to debug issues across Mobile and Desktops...

Caddy is very easy to do this, but hit an issue when I register a user:

https://app.localhost is mapped to the passkeys example running on port 8080 with no changes at all to it.

<img width="1728" alt="Screenshot 2024-08-08 at 14 20 07" src="https://github.com/user-attachments/assets/3dd7ad75-9eff-4758-8cc5-697bdb298c14">

## Caddy

caddy  run --config Caddyfile --adapter caddyfile

Caddyfile:

```sh
# Caddyfile
{
	log {
		output stdout
		format console
		level DEBUG
	}

	admin :2019
}

# https://localhost
localhost {
	file_server {
		root .
		browse
	} 
}

# https://hello.localhost
hello.localhost {
	respond "Hello world!"
}

# https://app.localhost
app.localhost {
	reverse_proxy :8080
}
```

**Comment by egregors** [comment]
Got the same error yesterday. I tried to run demo app in production mode (aws with let's encrypt ssl). 

I found the problem and fixed it, but not push it yet. I'll do it today later and check your PR of course:) 

BTW, after the fix I got it working on mobile Safari: 
![image](https://github.com/user-attachments/assets/cef45ab6-1307-430e-8886-830891ea7bb2)
![image](https://github.com/user-attachments/assets/0edfeeec-fcae-41f6-aa9e-c1cf7c8f5ab4)
![image](https://github.com/user-attachments/assets/60066350-1930-430c-bc38-ba4c9b9444bb)
